### ISSUE TITLE
거래시간 내림차순 정렬안됨

### ISSUE THREAD

**Issue by SongNoin** [wanted-pre-onboarding-fe-team-4/pre-onboarding-9th-4-4#16]
거래시간이 내림차순으로는 정렬되는데 오름차순으로는 안됩니다!
<img width="256" alt="스크린샷 2023-03-22 오후 7 42 11" src="https://user-images.githubusercontent.com/88178866/226878717-fae70406-a719-4870-978c-3f398595cca7.png">

**Comment by 2taesung** [comment]
요구사항에서 내림차순 밖에 없어서 내림차순만 추가했던걸로 기억합니다! 오름차순도 추가할까요 ?

**Comment by SongNoin** [comment]
아하 지금 보니까 그러네요!!! 제가 잘못본듯 ㅠ
요구사항이 없다면 굳이 필요하지 않을 것 같습니다!
